# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='profile_images', verbose_name='Світлина'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Емейл'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=128, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goodreads',
            field=models.CharField(blank=True, max_length=128, verbose_name='Goodreads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.CharField(blank=True, max_length=512, verbose_name='Iнформація'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=128, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=128, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=128, verbose_name='Twitter'),
        ),
    ]
