# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 16:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('short_descr', models.CharField(max_length=256, verbose_name='Короткий опис')),
                ('description', models.CharField(max_length=2000, verbose_name='Опис')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публікації')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos/projects', verbose_name='Світлина')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Посилання')),
                ('curators', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pub_date',),
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
