# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20180111_1854'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tag', to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='projects', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='photos/projects', verbose_name='Світлина'),
        ),
    ]
