# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-27 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180410_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Посилання'),
        ),
    ]
