# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_auto_20180111_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=200, verbose_name='Прізвище')),
                ('about_author', models.TextField(blank=True, verbose_name='Про автора')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публікації')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos/blog', verbose_name='Світлина')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Посилання')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'authors',
                'ordering': ('last_name',),
            },
        ),
    ]
