# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='profile_images')),
                ('info', models.CharField(max_length=512)),
                ('facebook', models.CharField(max_length=128)),
                ('twitter', models.CharField(max_length=128)),
                ('linkedin', models.CharField(max_length=128)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
