# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 16:54
from __future__ import unicode_literals

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('tags', '0002_auto_20180111_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_descr', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('from_author', models.TextField(blank=True, verbose_name='Від автора')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публікації')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos/books', verbose_name='Світлина')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ціна')),
                ('in_stock', models.CharField(blank=True, choices=[('Так', 'Так'), ('Ні', 'Ні'), ('Очікується', 'Очікується')], default='Тверда', max_length=10, verbose_name='У наявності')),
                ('pages', models.IntegerField(verbose_name='Сторінки')),
                ('cover', models.CharField(blank=True, choices=[('Тверда', 'Тверда'), ("M'яка", "M'яка")], default='Тверда', max_length=10, verbose_name='Обгортка')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вага (г)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Висота')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ширина')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Глибина')),
                ('publisher', models.IntegerField(default='Видавничий дім "Темпора"', verbose_name='Видавництво')),
                ('isbn_13', models.CharField(blank=True, max_length=15, verbose_name='ISBN-13')),
                ('isbn_10', models.CharField(blank=True, max_length=15, verbose_name='ISBN-10')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Посилання')),
                ('authors', models.ManyToManyField(blank=True, to='authors.Author')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'verbose_name_plural': 'books',
                'ordering': ('-title',),
            },
        ),
    ]
