# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Видавничий дім "Темпора"', max_length=90, verbose_name='Видавництво'),
        ),
    ]
