# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Посилання'),
        ),
    ]
