# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180329_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, choices=[('Hrd', 'Тверда'), ('Sft', "M'яка")], default='Hrd', max_length=3, verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='in_stock',
            field=models.CharField(blank=True, choices=[('0', 'Немає у наявності'), ('1', 'У наявності'), ('2', 'Очікується')], default='0', max_length=1, verbose_name='У наявності'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Посилання'),
        ),
    ]
