# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180329_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=90, verbose_name='Видавництво'),
        ),
    ]
