# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-27 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180124_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-pub_date',), 'verbose_name_plural': 'books'},
        ),
    ]
