# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-11 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180410_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='depth',
        ),
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рік видання'),
        ),
        migrations.AddField(
            model_name='book',
            name='translators',
            field=models.CharField(blank=True, max_length=200, verbose_name='Переклад'),
        ),
        migrations.AlterField(
            model_name='book',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Висота'),
        ),
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сторінки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вага (г)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Кількість'),
        ),
    ]
