# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-29 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180128_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, choices=[('Hrd', 'Тверда'), ('Sft', "M'яка")], default='Тверда', max_length=3, verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='in_stock',
            field=models.CharField(blank=True, choices=[('0', 'Немає у наявності'), ('1', 'У наявності'), ('2', 'Очікується')], default='Тверда', max_length=1, verbose_name='У наявності'),
        ),
    ]
