# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180627_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Сторінки'),
        ),
    ]
