# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Опрацьовано'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, verbose_name='Повідомлення'),
        ),
    ]
