# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-16 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180712_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Сторінки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Рік видання'),
        ),
    ]
