# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-28 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180228_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публікації'),
        ),
    ]
