# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-28 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20180716_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=512, verbose_name='Адреса доставки'),
        ),
    ]
