# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release',
            field=models.DateField(blank=True, null=True, verbose_name='Дата виходу'),
        ),
        migrations.AddField(
            model_name='book',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='Обрана книга'),
        ),
    ]
