# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20180304_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='best_seller',
            field=models.BooleanField(default=False, verbose_name='Топ продажів'),
        ),
        migrations.AddField(
            model_name='book',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
    ]
