# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20180828_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час опрацювання'),
        ),
    ]
