# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import easy_thumbnails.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', tinymce.models.HTMLField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos/blog')),
            ],
            options={
                'ordering': ('-pub_date',),
                'verbose_name_plural': 'posts',
            },
        ),
    ]
