# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
        ('blog', '0002_auto_20171130_2125'),
    ]

    operations = [
    ]
