# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-27 18:51
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180411_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_descr',
            field=tinymce.models.HTMLField(max_length=256, verbose_name='Короткий опис'),
        ),
    ]
