# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-14 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181227_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='Обраний'),
        ),
    ]
