# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-title',), 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='tag',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Назва'),
        ),
    ]
