# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-14 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0003_auto_20180411_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('short_descr', tinymce.models.HTMLField(max_length=256, verbose_name='Короткий опис')),
                ('selected', models.BooleanField(default=False, verbose_name='Обраний')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Посилання')),
                ('youtube', models.URLField(verbose_name='Youtube')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='tags.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'videos',
                'ordering': ('-pub_date',),
            },
        ),
    ]
